### ISSUE TITLE
Splitting and merging graphs

### ISSUE THREAD

**Issue by ericmjonas** [thejonaslab/tinygraph#11]
Per @oortsang 's suggestion, I think we should have functions for splitting and merging graphs. I think this includes: 
1. `g3 = merge(g1, g2, return_correspondence=False)` which returns the new graph and optionally (if `return_correspondence=True`) a tuple of two lists showing which nodes in g1 g2 correspond to nodes in g3 (so if g1 and g2 each have three nodes and the first three nodes of g3 are from g1 and the second three nodes of g3 are from g2 then this would be ([0, 1, 2], [3, 4, 5])
2. `gnew = subgraph(g1, node_list)` that returns the induced subgraph of g1 containing the nodes in `node_list`
3. Per @oortsang's other suggestion, a `graph_type_equality` check that checks if two graphs have the same adj dtype and same properties and prop dtypes. We should call this before `merge` and return a type error if they aren't compatible. 

We should be able to test merge and subgraph against each other in the test suite. I'd probably stick them in `util.py`.

**Comment by oortsang** [comment]
I think it's safe to close this issue?
